/**
 * Generates `golden-vectors.json` — the cross-language parity fixtures (§8).
 *
 * The TypeScript implementation is the generator; the Rust `commitment.rs` test reads
 * the same file and asserts it recomputes identical hashes. Run with:
 *
 *   pnpm --filter @casperproof/commitment gen:golden
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { canonicalize } from './canonical.js';
import { computeCommitment } from './commitment.js';
import type { GoldenVector, GoldenVectorFile, JsonValue } from './types.js';

interface VectorSpec {
  name: string;
  input: JsonValue;
  output: JsonValue;
  modelId: string;
  timestamp: number;
}

/**
 * Fixed, hand-picked vectors covering the canonicalization edge cases the parity test
 * must agree on: empty objects, nested objects, key-order sensitivity, arrays, unicode
 * (BMP), booleans/null, integer numbers, and the real risk-scorer / claim-oracle shapes.
 */
const SPECS: VectorSpec[] = [
  {
    name: 'empty-objects',
    input: {},
    output: {},
    modelId: 'casperproof-test-v1',
    timestamp: 0,
  },
  {
    name: 'key-order-insensitive',
    input: { b: 2, a: 1, c: { z: 26, a: 1 } },
    output: { score: 42, tier: 'LOW' },
    modelId: 'casperproof-riskscorer-v1',
    timestamp: 1718600000,
  },
  {
    name: 'risk-score-output',
    input: { address: 'account-hash-aabbcc', signals: 15 },
    output: {
      score: 73,
      tier: 'HIGH',
      decision: 'review',
      signals: { liquidity: 12, volatility: 88, counterpartyRisk: 60 },
    },
    modelId: 'casperproof-riskscorer-v1',
    timestamp: 1718600123,
  },
  {
    name: 'claim-oracle-output',
    input: { policyId: 7, observed: { trigger: 'oracle_failure', confidence: 95 } },
    output: { decision: 'payout', triggerType: 'oracle_failure', amount: '5000000000' },
    modelId: 'casperproof-claimoracle-v1',
    timestamp: 1718600456,
  },
  {
    name: 'unicode-and-types',
    input: { name: 'café', glyph: '漢字', ok: true, missing: null, items: [3, 2, 1] },
    output: { note: 'verified ✓', count: 3 },
    modelId: 'casperproof-test-v1',
    timestamp: 42,
  },
  {
    name: 'nested-arrays-objects',
    input: { matrix: [[1, 2], [3, 4]], meta: { tags: ['a', 'b'], n: 0 } },
    output: { flat: [1, 2, 3, 4] },
    modelId: 'casperproof-test-v1',
    timestamp: 9999999999,
  },
];

export function buildVectors(): GoldenVectorFile {
  const vectors: GoldenVector[] = SPECS.map((spec) => {
    const { inputHash, outputHash, commitment } = computeCommitment(spec);
    return {
      name: spec.name,
      input: spec.input,
      output: spec.output,
      modelId: spec.modelId,
      timestamp: spec.timestamp,
      canonicalInput: canonicalize(spec.input),
      canonicalOutput: canonicalize(spec.output),
      inputHash,
      outputHash,
      commitment,
    };
  });
  return {
    scheme:
      'commitment = blake2b_256( input_hash || output_hash || utf8(model_id) || le_u64(timestamp) )',
    hash: 'blake2b-256',
    note: 'Generated by @casperproof/commitment. The Rust commitment.rs test asserts parity.',
    vectors,
  };
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = join(here, '..', 'golden-vectors.json');
  const file = buildVectors();
  writeFileSync(outPath, `${JSON.stringify(file, null, 2)}\n`, 'utf8');
  console.log(`Wrote ${file.vectors.length} golden vectors to ${outPath}`);
}

// Run when invoked directly.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
