//! Shared on-chain commitment **types** (§8) — the trust anchor's Rust side.
//!
//! The `AttestationRegistry` stores and compares the bytes defined here; it **never**
//! recomputes hashes on-chain. All hashing (input/output/commitment) happens off-chain
//! in the TypeScript attestor and verifier (`@casperproof/commitment`).
//!
//! This module therefore contains only data types for storage. The cross-language
//! golden-vector parity test below (host-only, `#[cfg(test)]`) is the one place the
//! Rust side recomputes the scheme — purely to prove it agrees with the TypeScript
//! generator byte-for-byte.

use odra::casper_types::U512;
use odra::prelude::*;

/// A 32-byte blake2b-256 digest. Stored and compared as raw bytes on-chain.
pub type Hash = [u8; 32];

/// Lifecycle of an attestation.
#[odra::odra_type]
pub enum AttestationStatus {
    /// Live and within (or past) its dispute window, not challenged.
    Active,
    /// A challenge has been opened and awaits resolution.
    Challenged,
    /// Resolved as fraudulent; the attestor's stake was slashed.
    Slashed,
    /// Resolved as honest (challenge failed) or finalized after the window.
    Finalized,
}

impl AttestationStatus {
    /// Human-readable label used in error payloads / events.
    pub fn label(&self) -> &'static str {
        match self {
            AttestationStatus::Active => "Active",
            AttestationStatus::Challenged => "Challenged",
            AttestationStatus::Slashed => "Slashed",
            AttestationStatus::Finalized => "Finalized",
        }
    }
}

/// An attestation record. On-chain = hashes + metadata + stake; the full payload lives
/// off-chain in the S3-compatible store, addressed by `uri`.
#[odra::odra_type]
pub struct Attestation {
    pub id: u64,
    pub attestor: Address,
    /// e.g. `casperproof-riskscorer-v1`.
    pub model_id: String,
    /// `blake2b_256(canonical_bytes(input))`.
    pub input_hash: Hash,
    /// `blake2b_256(canonical_bytes(output))`.
    pub output_hash: Hash,
    /// `blake2b_256(input_hash || output_hash || utf8(model_id) || le_u64(timestamp))`.
    pub commitment: Hash,
    /// S3 object URL for the off-chain payload (content-addressed by hash).
    pub uri: String,
    /// Stake locked behind this attestation (CEP-18 STAKE motes).
    pub stake: U512,
    pub created_at: u64,
    pub status: AttestationStatus,
    /// The account that opened a challenge, if any.
    pub challenger: Option<Address>,
    /// Bond posted by the challenger.
    pub challenge_bond: U512,
    pub challenged_at: u64,
}

/// Per-attestor reputation, updated on every resolution.
#[odra::odra_type]
pub struct Reputation {
    /// Total attestations submitted.
    pub total: u64,
    /// Attestations that survived (finalized honest).
    pub successful: u64,
    /// Attestations slashed as fraudulent.
    pub slashed: u64,
    /// Challenges this attestor defended successfully.
    pub challenges_defended: u64,
}

impl Default for Reputation {
    fn default() -> Self {
        Reputation {
            total: 0,
            successful: 0,
            slashed: 0,
            challenges_defended: 0,
        }
    }
}

/// Registry configuration, set at deploy time.
#[odra::odra_type]
pub struct RegistryConfig {
    /// Minimum stake required to submit an attestation.
    pub min_stake: U512,
    /// Bond a challenger must post.
    pub challenge_bond: U512,
    /// Dispute window in seconds; challenges are only accepted within it.
    pub dispute_window: u64,
    /// Treasury that receives the protocol's cut of a slash.
    pub treasury: Address,
    /// Account authorized to resolve challenges.
    pub resolver: Address,
    /// Challenger reward, in basis points of the slashed stake (e.g. 5000 = 50%).
    pub reward_bps: u64,
}

// ──────────────────────────────────────────────────────────────────────────────
// Cross-language golden-vector parity test (HOST-ONLY).
//
// Recomputes the §8 scheme in Rust and asserts it matches the vectors generated by
// the TypeScript `@casperproof/commitment` package, byte-for-byte. This guards the
// invariant that the contract, attestor, and verifier all agree on the commitment.
// ──────────────────────────────────────────────────────────────────────────────
#[cfg(test)]
mod golden_parity {
    use blake2::digest::{Update, VariableOutput};
    use blake2::Blake2bVar;
    use serde::Deserialize;
    use serde_json::Value;

    /// blake2b-256 (32-byte digest) — must match `@noble/hashes` `blake2b(..., {dkLen:32})`.
    fn blake2b256(data: &[u8]) -> [u8; 32] {
        let mut hasher = Blake2bVar::new(32).expect("valid output size");
        hasher.update(data);
        let mut out = [0u8; 32];
        hasher.finalize_variable(&mut out).expect("32-byte output");
        out
    }

    /// Canonical JSON matching the TS canonicalizer (§8): object keys sorted ascending,
    /// compact (no whitespace), UTF-8, integer numbers. We sort keys explicitly because
    /// serde_json is built with `preserve_order` in this dependency tree (via casper-types),
    /// so it would otherwise keep insertion order. String escaping is delegated to
    /// serde_json, which matches `JSON.stringify` for the BMP/ASCII payloads we use.
    fn canonical(value: &Value) -> String {
        let mut out = String::new();
        write_canonical(value, &mut out);
        out
    }

    fn write_json_string(s: &str, out: &mut String) {
        out.push_str(&serde_json::to_string(s).expect("string serializes"));
    }

    fn write_canonical(value: &Value, out: &mut String) {
        match value {
            Value::Null => out.push_str("null"),
            Value::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
            Value::Number(n) => out.push_str(&n.to_string()),
            Value::String(s) => write_json_string(s, out),
            Value::Array(arr) => {
                out.push('[');
                for (i, v) in arr.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    write_canonical(v, out);
                }
                out.push(']');
            }
            Value::Object(map) => {
                let mut keys: Vec<&String> = map.keys().collect();
                keys.sort();
                out.push('{');
                for (i, key) in keys.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    write_json_string(key, out);
                    out.push(':');
                    write_canonical(&map[*key], out);
                }
                out.push('}');
            }
        }
    }

    #[derive(Deserialize)]
    struct GoldenFile {
        vectors: Vec<Vector>,
    }

    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Vector {
        name: String,
        input: Value,
        output: Value,
        model_id: String,
        timestamp: u64,
        canonical_input: String,
        canonical_output: String,
        input_hash: String,
        output_hash: String,
        commitment: String,
    }

    const GOLDEN: &str = include_str!("../../packages/commitment/golden-vectors.json");

    #[test]
    fn rust_matches_typescript_golden_vectors() {
        let file: GoldenFile = serde_json::from_str(GOLDEN).expect("valid golden-vectors.json");
        assert!(!file.vectors.is_empty(), "expected golden vectors");

        for v in &file.vectors {
            // 1. Canonicalization parity (key sorting, compaction, unicode).
            let ci = canonical(&v.input);
            let co = canonical(&v.output);
            assert_eq!(ci, v.canonical_input, "canonicalInput mismatch [{}]", v.name);
            assert_eq!(co, v.canonical_output, "canonicalOutput mismatch [{}]", v.name);

            // 2. input_hash / output_hash parity.
            let ih = blake2b256(ci.as_bytes());
            let oh = blake2b256(co.as_bytes());
            assert_eq!(hex::encode(ih), v.input_hash, "inputHash mismatch [{}]", v.name);
            assert_eq!(hex::encode(oh), v.output_hash, "outputHash mismatch [{}]", v.name);

            // 3. commitment parity: blake2b_256(ih || oh || utf8(model_id) || le_u64(ts)).
            let mut preimage = Vec::with_capacity(32 + 32 + v.model_id.len() + 8);
            preimage.extend_from_slice(&ih);
            preimage.extend_from_slice(&oh);
            preimage.extend_from_slice(v.model_id.as_bytes());
            preimage.extend_from_slice(&v.timestamp.to_le_bytes());
            let commitment = blake2b256(&preimage);
            assert_eq!(
                hex::encode(commitment),
                v.commitment,
                "commitment mismatch [{}]",
                v.name
            );
        }
    }

    #[test]
    fn blake2b256_matches_known_vectors() {
        // Standard BLAKE2b-256 vectors (must equal the TS hash.test.ts values).
        assert_eq!(
            hex::encode(blake2b256(b"")),
            "0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8"
        );
        assert_eq!(
            hex::encode(blake2b256(b"abc")),
            "bddd813c634239723171ef3fee98579b94964e3bb1cb3e427262c8c068d52319"
        );
    }
}
